#!/bin/bash

GREEN='\033[0;32m' 
NC='\033[0m' # No Color

# Test 1: Test call function
twx-call-test.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 2: Import a single XML file
twx-import-single-entity-test.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 3: Import a directory containing XML files
twx-import-folder-test.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 4: Import an extension
twx-import-extension-test.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 5: Import a directory containing XML files
twx-eval-test.sh
if [ $? -ne 0 ]; then exit 1; fi

printf "All tests complited ${GREEN}successfully${NC}\n"