#!/bin/bash

GREEN='\033[0;32m' 
NC='\033[0m' # No Color

# Test 1: Test call function
twxCallTest.sh
if [ $? -ne 0 ]; then exit 1; fi
# Test 2: Import a single XML file
twxImportSingleEntityTest.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 3: Import a directory containing XML files
twxImportFolderTest.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 4: Import an extension
twxImportExtensionTest.sh
if [ $? -ne 0 ]; then exit 1; fi

# Test 5: Import a directory containing XML files
twxEvalTest.sh
if [ $? -ne 0 ]; then exit 1; fi

printf "All tests complited ${GREEN}successfully${NC}\n"