#!/bin/bash

# Test 1: Test call function
./twxCallTest.sh

# Test 2: Import a single XML file
./twxImportSingleEntityTest.sh

# Test 3: Import a directory containing XML files
./twxImportFolderTest.sh

# Test 4: Import an extension
./twxImportExtensionTest.sh

# Test 5: Import a directory containing XML files
./twxEvalTest.sh

echo "All tests completed succesfully"